name: Test Call CKB

on:
  push:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout axon-call-precompiles
      uses: actions/checkout@v3
    - name: Checkout Axon
      uses: actions/checkout@v3
      with:
        ref: refactor-precompile-input
        repository: axonweb3/axon
        path: components/axon
    - name: Checkout axonweb3/emitter
      uses: actions/checkout@v3
      with:
        ref: joyid-debug
        repository: axonweb3/emitter
        path: components/emitter

    - run: pwd & ls
      if: always()

    - run: ls $GITHUB_WORKSPACE
      if: always()

    - run: du -hd2
      if: always()

    - name: Cache of Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          components/axon/target/
          components/emitter/target/
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-cargo

    - name: Build Axon
      working-directory: components/axon
      run: cargo build
